apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji-voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-voting
  template:
    metadata:
      labels:
        app: emoji-voting
    spec:
      containers:
      - image: atbb/emojivoto-voting-svc:v11
        name: emoji-voting
        envFrom:
        - configMapRef:
            name: emoji-config
         
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-voting
spec:
  selector:
    app: emoji-voting
  ports:
  - name: emoji-voting
    port: 9000
    targetPort: 9000
    protocol: TCP